In [21]:
# import only required libraries
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures



df_team = pd.read_csv('../data/raw/matches_20000.csv')

/var/folders/g8/n22h2t4s6rb9cx2pnxzsdxk80000gp/T/ipykernel_78895/2548779081.py:10: DtypeWarning: Columns (94) have mixed types. Specify dtype option on import or set low_memory=False.
  df_team = pd.read_csv('../data/raw/matches_20000.csv')

In [25]:
df_team

,match_id,start_time,radiant_team_id,radiant_name,dire_team_id,dire_name,leagueid,league_name,series_type,region,...,team2_hero1_wins,team2_hero2_gamesPlayed,team2_hero2_wins,team2_hero3_gamesPlayed,team2_hero3_wins,team2_hero4_gamesPlayed,team2_hero4_wins,team2_hero5_gamesPlayed,team2_hero5_wins,radiant_win
0,7679791994,1712766652,8574561.0,Azure Ray,2586976.0,OG,16483,Elite League by FISSURE and ESB,3.0,3.0,...,56.0,25.0,11.0,177.0,101.0,94.0,56.0,53.0,26.0,False
1,7679791197,1712766461,9209880.0,Prodigy Of God,8831040.0,Ghost Sheep,15901,Ultras Dota Pro League 2023-24,1.0,8.0,...,255.0,67.0,39.0,86.0,48.0,22.0,12.0,38.0,24.0,True
2,7679784808,1712766601,8255888.0,BetBoom Team,7732977.0,BOOM Esports,16483,Elite League by FISSURE and ESB,3.0,3.0,...,81.0,7.0,4.0,51.0,30.0,25.0,18.0,27.0,19.0,True
3,7679771773,1712765505,9344594.0,Dominion,9397016.0,Elite Eclips,15901,Ultras Dota Pro League 2023-24,1.0,8.0,...,2.0,2.0,2.0,1.0,1.0,4.0,2.0,4.0,3.0,False
4,7679708072,1712762996,9209880.0,Prodigy Of God,8831040.0,Ghost Sheep,15901,Ultras Dota Pro League 2023-24,1.0,8.0,...,34.0,65.0,35.0,73.0,36.0,141.0,74.0,45.0,20.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,7289930641,1692339416,8629315.0,Wiser Warriors,8629317.0,Bright Crusaders,15026,Destiny league,1.0,3.0,...,14.0,81.0,47.0,68.0,37.0,106.0,57.0,67.0,32.0,False
19996,7289926197,1692339282,8582076.0,Team Disillusion,9018710.0,Holy Grail,15689,Road to TI 2023 - CN Regional Qualifiers,1.0,17.0,...,13.0,22.0,13.0,19.0,15.0,13.0,10.0,10.0,4.0,False
19997,7289913798,1692338142,8961813.0,SHAOLIN,8893825.0,Lucky Bulldogs,15480,Ancients League,1.0,3.0,...,24.0,100.0,50.0,8.0,5.0,8.0,3.0,57.0,28.0,True
19998,7289887554,1692336286,8629317.0,Bright Crusaders,8629315.0,Wiser Warriors,15026,Destiny league,1.0,3.0,...,153.0,149.0,80.0,125.0,66.0,198.0,98.0,395.0,195.0,False
19999,7289878493,1692335558,8864178.0,Marvelous Warriors,9018528.0,Crew X,15480,Ancients League,1.0,3.0,...,12.0,44.0,24.0,109.0,59.0,70.0,41.0,57.0,32.0,True

In [24]:
# Get Unique Ids From Randia and dire team


df_radian = df_team[['radiant_team_id', 'radiant_name']]
df_dire = df_team[['dire_team_id', 'dire_name']]

# Get Unique Ids From Randia and dire team

df_radian = df_radian.drop_duplicates()
df_dire = df_dire.drop_duplicates()

# Get Unique Ids From Randia and dire team

#change name columns

df_radian.columns = ['team_id', 'team_name']

df_dire.columns = ['team_id', 'team_name']


# Merge the two dataframes

df_teams = pd.concat([df_radian, df_dire])

# Drop duplicates

df_teams = df_teams.drop_duplicates()


## Save into Json with id and name

df_teams.to_json('../data/processed/teams.json', orient='records')

     radiant_team_id    radiant_name  dire_team_id       dire_name
0          8574561.0       Azure Ray     8574561.0       Azure Ray
1          9209880.0  Prodigy Of God     9209880.0  Prodigy Of God
2          8255888.0    BetBoom Team     8255888.0    BetBoom Team
3          9344594.0        Dominion     9344594.0        Dominion
4          9397016.0    Elite Eclips     9397016.0    Elite Eclips
..               ...             ...           ...             ...
804        9018279.0     rombiki 3.0     9018279.0     rombiki 3.0
805        9092294.0    Unlucky Team     9092294.0    Unlucky Team
806        7453020.0     Aster.Aries     7453020.0     Aster.Aries
807        9149226.0   Team Flamingo     9149226.0   Team Flamingo
808        8943671.0       Supernova     8943671.0       Supernova

[809 rows x 4 columns]